-- AlterTable
ALTER TABLE "Map" ALTER COLUMN "width" SET DATA TYPE TEXT,
ALTER COLUMN "height" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "mapElements" ALTER COLUMN "x" SET DATA TYPE TEXT,
ALTER COLUMN "y" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "spaceElements" ALTER COLUMN "x" SET DATA TYPE TEXT,
ALTER COLUMN "y" SET DATA TYPE TEXT;
